### ISSUE TITLE
[DEV-548] [DEV-549] bug: font (style) bug for data upload component

### ISSUE THREAD

**Issue by ObservedObserver** [Kanaries/graphic-walker#281] opened 2023-12-28 04:15 UTC
![image](https://uploads.linear.app/f81e7bd9-c8ca-4dfb-b242-4b047e948d40/cfd194a0-7e22-4ddb-ad71-60b98f1430fd/8f80b5a4-c7fb-42ef-a3d7-bbc0a34b2733?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y4MWU3YmQ5LWM4Y2EtNGRmYi1iMjQyLTRiMDQ3ZTk0OGQ0MC9jZmQxOTRhMC03ZTIyLTRkZGItYWQ3MS02MGI5OGYxNDMwZmQvOGY4MGI1YTQtYzdmYi00MmVmLWEzZDctYmJjMGEzNGIyNzMzIiwiaWF0IjoxNzAzNzM2OTM5LCJleHAiOjE3MDM4MjMzMzl9.WoYpZCuqpOpYUeSDQoe9SrN8wRw_GLpiTFiWpulVnLg)

<sub>From [SyncLinear.com](https://synclinear.com) | [DEV-548](https://linear.app/kanaries/issue/DEV-548/[dev-549]-bug-font-style-bug-for-data-upload-component)</sub>

**Comment by shubhamku044** [comment] 2023-12-28 07:27
I would like to work on this issue

**Comment by BassCoder2808** [comment] 2024-01-03 17:43
Hi @ObservedObserver I would like to work on this issue if it is still open, can you please tell exactly what needs to be done because the image is not visible I think or else can you please reupload the image if the issue is still persists

**Comment by ObservedObserver** [comment] 2024-01-12 00:46
![image](https://github.com/Kanaries/graphic-walker/assets/22167673/26c4e8f4-6290-4832-81f7-c78285bb5e49)

![image](https://github.com/Kanaries/graphic-walker/assets/22167673/489aa2ee-0c72-4195-8587-d2b41f0efc4e)

Data Source Component has some styles bug where font family is not displayed correctly.

Welcome to make a PR if you are interested in fixing it. There was a similar issue happened before which you can check at https://github.com/Kanaries/graphic-walker/pull/242

**Comment by islxyqwe** [comment] 2024-02-02 09:52
fixed in #297

**Closed by islxyqwe** 2024-02-02 09:52 UTC
Labels: bug, good first issue, linear
